// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Definition of a Serverless VPC Access connector.
public struct Connector: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The resource name in the format `projects/*/locations/*/connectors/*`.
  public var name: Swift.String = Swift.String()

  /// Name of a VPC network.
  public var network: Swift.String = Swift.String()

  /// The range of internal addresses that follows RFC 4632 notation.
  /// Example: `10.132.0.0/28`.
  public var ipCidrRange: Swift.String = Swift.String()

  /// Output only. State of the VPC access connector.
  public var state: Connector.State = Connector.State()

  /// Minimum throughput of the connector in Mbps. Default and min is 200.
  public var minThroughput: Swift.Int32 = Swift.Int32()

  /// Maximum throughput of the connector in Mbps. Default is 300, max is 1000.
  public var maxThroughput: Swift.Int32 = Swift.Int32()

  /// Output only. List of projects using the connector.
  public var connectedProjects: [Swift.String] = []

  /// The subnet in which to house the VPC Access Connector.
  public var subnet: Connector.Subnet? = nil

  /// Machine type of VM Instance underlying connector. Default is e2-micro
  public var machineType: Swift.String = Swift.String()

  /// Minimum value of instances in autoscaling group underlying the connector.
  public var minInstances: Swift.Int32 = Swift.Int32()

  /// Maximum value of instances in autoscaling group underlying the connector.
  public var maxInstances: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `Connector`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Connector().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The subnet in which to house the connector
  public struct Subnet: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Subnet name (relative, not fully qualified).
    /// E.g. if the full subnet selfLink is
    /// https://compute.googleapis.com/compute/v1/projects/{project}/regions/{region}/subnetworks/{subnetName}
    /// the correct input for this field would be {subnetName}
    public var name: Swift.String = Swift.String()

    /// Project in which the subnet exists.
    /// If not set, this project is assumed to be the project for which
    /// the connector create request was issued.
    public var projectId: Swift.String = Swift.String()

    /// Initialize a new instance of `Subnet`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Subnet().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.vpcaccess.v1.Connector.Subnet"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// State of a connector.
  public enum State: Codable, Equatable, Sendable {
    /// Invalid state.
    case unspecified
    /// Connector is deployed and ready to receive traffic.
    case ready
    /// An Insert operation is in progress. Transient condition.
    case creating
    /// A Delete operation is in progress. Transient condition.
    case deleting
    /// Connector is in a bad state, manual deletion recommended.
    case error
    /// The connector is being updated.
    case updating
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .ready: return 1
      case .creating: return 2
      case .deleting: return 3
      case .error: return 4
      case .updating: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .ready: return "READY"
      case .creating: return "CREATING"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .updating: return "UPDATING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "READY": self = .ready
      case "CREATING": self = .creating
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "UPDATING": self = .updating
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .ready
      case 2: self = .creating
      case 3: self = .deleting
      case 4: self = .error
      case 5: self = .updating
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .ready: return try container.encode(1)
      case .creating: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .error: return try container.encode(4)
      case .updating: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.vpcaccess.v1.Connector"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
